# Generated by `make brew-formula` — edit Formula/claude-account.rb.in, not the .rb.
class ClaudeAccount < Formula
  desc "Route Claude Code subscriptions per project path (macOS)"
  homepage "https://github.com/reddeer-tech/claude-account"
  url "https://github.com/reddeer-tech/claude-account/releases/download/v1.0.16/claude-account-1.0.16.tar.gz"
  sha256 "5a18717d5396f595370e50d0c4d4315463a04cc8526ba6feeb2de9f2d03c10d3"
  license "MIT"
  depends_on :macos

  def install
    libexec.install "libexec/resolve.sh"
    bin.install "bin/claude-account"
    bin.install "bin/claude-whoami"
    # The routing shims must be able to shadow the real `claude`, so they are NOT
    # linked into bin/ automatically — that would hijack claude for every caller
    # before the user has opted in. `claude-account setup` links them on request.
    (libexec/"shims").install "bin/claude-shim", "bin/claude-vscode-wrapper"
    pkgshare.install "templates"
  end

  def caveats
    <<~EOS
      Routing is not active until you opt in:

        claude-account setup        # links the claude shim ahead of the real one
        claude-account doctor       # verifies PATH order and the VS Code wrapper

      macOS only: uses the Keychain and VS Code's settings path.
    EOS
  end

  test do
    assert_match "claude-account", shell_output("#{bin}/claude-account --help")
  end
end
