# Generated by `make brew-formula` — edit Formula/sshid.rb.in, not the .rb.
class Sshid < Formula
  desc "Route SSH keys and gh accounts per repository (macOS)"
  homepage "https://github.com/reddeer-tech/sshid"
  url "https://github.com/reddeer-tech/sshid/releases/download/v1.0.5/sshid-1.0.5.tar.gz"
  sha256 "966b2a079d56c31408eaa3288f81b9c940813aa48a64a09114f052a5d3faf5e4"
  license "MIT"
  depends_on :macos

  def install
    libexec.install "libexec/lib.sh", "libexec/resolve.sh"
    bin.install "bin/sshid"
    # The gh shim has to be able to shadow the real `gh`, so it is NOT linked into bin/.
    # Installing this package must never hijack a command before the user has opted in;
    # `sshid setup` puts it on PATH on request.
    (libexec/"shims").install "libexec/gh-shim"
    pkgshare.install "templates"
  end

  def caveats
    <<~EOS
      Nothing is routed until you opt in:

        sshid setup     install the resolver, and the gh shim if you have gh
        sshid adopt     import the routing already on this machine
        sshid doctor    check it

      sshid does not bundle gh. If you have gh, the shim hands off to it and your
      existing logins keep working. If you do not, ssh routing works without it.

      macOS only.
    EOS
  end

  test do
    assert_match "sshid", shell_output("#{bin}/sshid --version")
  end
end
